DISABLE_PRINT = false
DISABLE_SHELL = true
DISABLE_MKDIR = false
DISABLE_FILE = false
DISABLE_DOWNLOAD = false
DISABLE_UNZIP = false
DISABLE_ALIAS = false
DISABLE_DELETE = true
PRINT_IF_COMMAND_DISABLED = false
PROMPT_USER_FOR_BIG_DOWNLOADS = true
BIG_DOWNLOAD_SIZE_MB = 100
PROMPT_USER_FOR_EVERY_COMMAND = false
PROMPT_USER_FOR_DANGEROUS_COMMANDS = true
ALLOWED_SHELL_COMMANDS = ["printf", "echo", "ls", "dir", "cat", "type", "head", "tail", "more", "less", "cd", "pwd", "whoami"]
BLACKLISTED_SHELL_COMMANDS = ["rm", "del", "mv", "move", "cp", "copy", "shutdown", "reboot", "init 0", "init 6"]
IGNORE_ALL_SAFETY_MEASURES_INCLUDING_DISABLING_AND_SHELL_COMMAND_BLACKLISTING_VERY_DANGEROUS = false
LOG_FILE_PATH = "pyspew.log"
MAX_LOG_FILE_SIZE_MB = 5
ALLOW_EXECUTING_OF_DIFFERENT_OS_COMMANDS = false
DEBUG = true
UNZIP_BACKEND_WINDOWS = "powershell -Command \"Expand-Archive -Path \\\"{file_path}\\\" -DestinationPath \\\"{destination_path}\\\"\""
UNZIP_BACKEND_LINUX = "unzip \"{file_path}\" -d \"{destination_path}\""
UNZIP_BACKEND_OSX = "unzip \"{file_path}\" -d \"{destination_path}\""
SHELL_USED_ON_LINUX = "/bin/bash"
SHELL_USED_ON_OSX = "/bin/bash"
SHELL_USED_ON_WINDOWS = "cmd.exe"